data:
  dataset_name: "MVSEC"
  data_path: "/run/determined/workdir/data/MVSEC/hdf5"
  load_gt_flow: True
  gt_path: "/run/determined/workdir/data/MVSEC/flow_gt"
  sequence: "indoor_flying1"
  hight: 260
  width: 346
  eval_dt: 4
  loader:
    num_workers: 16
    batch_size: 32
    shuffle: True
    pin_memory: True

logger:
  project: mvsec_indoor_flying_1_test_spline
  expname: cmax_1e-46_dec_1e-2_weight_2.5_total_iter_10000_exp
  results_dir: ./outputs/${project}/${expname}
  model_weight_path: ./weights/${project}_${expname}.pth

model:
  pos_encode: False
  multires: 2

optimizer:
  nn_lr_1: 1.0e-4
  nn_lr_2: 1.0e-5
  nn_lr_3: 1.0e-6
  spline_lr_1: 1.0e-1
  spline_lr_2: 1.0e-2
  num_epoch: 10000

warp:
  tref_setting: "random"
  solver: "euler"
  rtol: 1.0e-7
  atol: 1.0e-9