data:
  dataset_name: SyntheticFigure
  data_path: /run/determined/workdir/ssd_data/Event_Dataset/Blender/final_motion_boxes
  hight: 480
  weight: 640
  color_event: False
  threshold: 0.2
  sequence_indices: [0,19]
  batch_range: 15
  loader:
    num_workers: 16
    batch_size: 32
    shuffle: True
    pin_memory: True

logger:
  project: Blender_final_motion_boxes
  expname: sequence_0to19
  results_dir: ./outputs/${project}/${expname}
  model_weight_path: ./weights/${project}_${expname}.pth

model:
  pos_encode: False
  multires: 10

optimizer:
  initial_lrate: 1.0e-4
  final_lrate: 1.0e-6
  num_epoch: 500

warp:
  num_step: 3
  tref_setting: "multi"
  solver: "euler"

valid: 
  file_idx: [0,19]
    