data:
  dataset_name: SimpleTest
  data_path: "/run/determined/workdir/ssd_data/NeuEF_SimpleTest/synthetic"
  hight: 480
  weight: 640
  color_event: False
  threshold: 0.2
  sequence_indices: [49,99]
  batch_range: 15
  loader:
    num_workers: 16
    batch_size: 32
    shuffle: True
    pin_memory: True

logger:
  project: "test_evaluation"
  expname: "test_pth_evaluate"
  results_dir: "./outputs/"
  model_weight_path: "./weights/test.pth"

model:
  pos_encode: False
  multires: 10

optimizer:
  initial_lrate: 1.0e-4
  final_lrate: 1.0e-6
  num_epoch: 300

warp:
  num_step: 3
  tref_setting: "multi"
  solver: "euler"

valid: 
  file_idx: [49,99]