data:
  dataset_name: "DSEC"
  data_path: "/run/determined/workdir/data/DSEC/test_events"
  timestamp_path: "/run/determined/workdir/data/DSEC/test_forward_optical_flow_timestamps"
  sequence: "interlaken_00_b"
  hight: 480
  width: 640
  loader:
    num_workers: 16
    batch_size: 32
    shuffle: True
    pin_memory: True

logger:    
  project: dsec_full_model_exp
  expname: interlaken_00_b
  results_dir: ./outputs/${project}/${expname}
  model_weight_path: ./weights/${project}_${expname}.pth

loss:
  cmax: True
  ssl_dec: True
  sl_dec: False
  smooth: True  

model:
  pos_encode: True
  multires: 6
  nn_depth: 8
  nn_width: 256

optimizer:
  nn_initial_lr: 2.0e-3
  nn_final_lr: 1.0e-7
  spline_lr: 1.0e-3
  num_iters: 1000
  warmup_steps: 100

warp:
  tref_setting: "random"
  solver: "euler"
  step_size: 10
  rtol: 1.0e-7
  atol: 1.0e-9

early_stopping:
  enabled: False
  burn_in_steps: 300     
  patience: 45          
  min_delta: 1.0e-3       
  percentage: false  