data:
  dataset_name: "MVSEC"
  data_path: "/run/determined/workdir/data/MVSEC/hdf5"
  load_gt_flow: True
  gt_path: "/run/determined/workdir/data/MVSEC/flow_gt"
  sequence: "outdoor_day1"
  hight: 260
  width: 346
  eval_dt: 4
  n_events_per_batch: 40000
  remove_car: True
  valid_frame_1: 10157
  valid_frame_2: 10957
  loader:
    num_workers: 16
    batch_size: 32
    shuffle: True
    pin_memory: True

logger:
  project: mvsec_full_model_results
  expname: outdoor_day_1_dt_4
  results_dir: ./outputs/${project}/${expname}
  model_weight_path: ./weights/${project}_${expname}.pth

loss:
  cmax: True
  ssl_dec: True
  sl_dec: False

model:
  pos_encode: False
  multires: 2
  
optimizer:
  nn_initial_lr: 1.0e-4
  nn_final_lr: 6.3e-5
  spline_lr: 1.0e-3
  num_iters: 1000

warp:
  tref_setting: "random"
  solver: "euler"
  step_size: 10
  rtol: 1.0e-7
  atol: 1.0e-9

early_stopping:
  enabled: True
  burn_in_steps: 300     
  patience: 45          
  min_delta: 1.0e-3       
  percentage: false     